# -*- coding: utf-8 -*-
"""ASISTIDO/BSCS3A

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IYcc-z3-CmC7ts1UNVIO2WkUNL_Uzbni

**MY FIRST R PROGRAM**
"""

print ("I love R Prog")

print ("I love R Prog")

cat ("R", "Prog")

"""**Variables & Data Types**"""

myString <- "I love u"
wholeNum <- 10
floatingNum <- 9.9
isBool <- TRUE

print (myString)

class(myString)
class(wholeNum)
class(floatingNum)
class(isBool)

"""**NUMERICAL OPERATOR**"""

x <- 10
y <- 3
z <- x + y

add <- x + y #Addition
sub <- x - y #Subtraction
mul <- x * y #Multiplication
div <- x / y #Division
mod <- x %% y #Modulus
mod <- x ^ y #Exponent


print(add)
print(sub)
print(mul)
print(div)
print(mod)
print(exp)

print(z)

"""**USER INPUT**"""

name <- readline("Enter your name")

cat ("hello to the R prog: ", name)

"""**DECISION MAKING**"""

grade <- 80

if (grade < 75 ){
  print ("failed")
}else{
  print ("passed")
}

"""**LOOP**"""

for (i in 1:6){  print (i)
}

"""**FUNCTIONS**"""

addNumber <- function(a,b){
  return(a+b)
}

addNumber(3,7)

"""**VECTORS**"""

grades <- c(99,80,98,97,95)

grades

cat("Mean: ",mean(grades))
cat("\nmax:",max(grades))
cat("\nMin: ",min(grades))
cat("\nlength:",length(grades))
cat("\nMedian: ",median(grades))

"""**MATRICES**"""

A <- matrix(c(1,2,3,4,5,6),nrow=2)
A

"""**LIST**"""

students <- list(
  Name = "John Kurt",
  Course = "BSCS",
  Grade = 65
)

students

"""**DATA FRAME**"""

students <- data.frame(
  name = c("JK", "LABAHO", "HAHA"),
  course = c("BSCS", "BSIT", "BS Comp Vulca"),
  grade = c(94,96,99)
  )

  students

"""**WRITE to CSV**"""

write.csv(students, "students.csv")

"""**READ CSV FILE**"""

data <- read.csv("students.csv")
head(data)
summary(data)